# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 5                     # nombre de liens “autour” de la page courante
    default_options:
        page_name: page               # le paramètre GET pour la page (exemple ?page=2)
        sort_field_name: sort         # si vous souhaitez ajouter du tri
        sort_direction_name: direction
        distinct: true                # empêche les doublons quand Doctrine génère le COUNT
        filter_field_name: filterField
        filter_value_name: filterValue
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
