controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
home:
    path: /
    controller: App\Controller\DefaultController::index
user_index:
    path: /user
    controller: App\Controller\UserController::index
